version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    depends_on:
      - db
    ports:
      - 3030:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: narrator
      WORDPRESS_DB_PASSWORD: password1
      WORDPRESS_DB_NAME: storytime
      WORDPRESS_DB_PORT: 3307
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG', true );
        define( 'WP_DEBUG_DISPLAY', true );
        define( 'WP_DEBUG_LOG', '/var/www/html/wp-content/logs/debug.log');
    volumes:
      - ./wp_files/wordpress:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./storytime:/var/www/html/wp-content/plugins/storytime

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: storytime
      MYSQL_USER: narrator
      MYSQL_PASSWORD: password1
      MYSQL_ROOT_PASSWORD: password1
    volumes:
      - ./wp_files/db:/var/lib/mysql
